### PR TITLE
Fix for stage priority flow and other KSP 1.2 changes

### PR DESCRIPTION
**Pull request by Gerry1135**
This fixes the deltaV calculation problem reported with multi-stage ion engine vessels in this post (and also earlier in the KER thread):

http://forum.kerbalspaceprogram.com/index.php?/topic/143694-stage_priority-delta-v-calculation/

### CODE REVIEW

**Comment by Gerry1135** [comment]
I'm going to release a test version of this on my DropBox so we can get some feedback before it gets merged.

**Comment by cloudynetwork** [comment]
@Gerry1135 Does this run on 1.2 as is?

**Comment by deadhead420** [comment]
Please do! Just updated to 1.2 and could use something which actually works

**Comment by cloudynetwork** [comment]
@Gerry1135 @deadhead420 
Does somebody have a build with this fix I can download later?

**Comment by deadhead420** [comment]
@cloudynetwork have been searching for one for the past hour now. I'll let you know if I find anything which works.

**Comment by deadhead420** [comment]
@cloudynetwork Got it man. I just checked in @Gerry1135's repo. Just tested and its working just fine in 1.2

**Comment by cloudynetwork** [comment]
@deadhead420 I may look at forking this and having Travis build it automatically....although no idea when I'll get a chance to do that.

**Comment by deadhead420** [comment]
@cloudynetwork here is the link where I got the updated version: https://github.com/Gerry1135/KerbalEngineer/tree/7959d0d280c934b42b960c2bfba62ea112d6ea2f

You will notice a folder called output. Inside is KerbalEngineer. That is the latest build and seems to be working just fine. I will report back here if I run into any bugs

**Comment by deadhead420** [comment]
@Gerry1135 Thanks for your fixes!

**Comment by Gerry1135** [comment]
I posted a link to download this version in the KER forum thread:

http://forum.kerbalspaceprogram.com/index.php?/topic/17833-111-kerbal-engineer-redux-1110-2016-04-29/&page=135#comment-2808910

**Comment by fommil** [comment]
Looking good so far on 1.2.1 (after manually hacking the version file... using the hotfix version). Lost all my setups (window locations / contents), is that an expected regression?

**Pull request merged**
