### PR TITLE
Added Deceleration Readouts

### PR DESCRIPTION
**Pull request by harryyoung**
Added Deceleration Readouts to Vessel Section. The Basic Idea is like the Suicide Burn, but with the Added bonus of Horizontal Velocity, the ability to do it from Orbit and a lot of additional Readouts like Lat/Lon, Altitude at landing Site, Slope, biome etc.

Closes https://github.com/CYBUTEK/KerbalEngineer/issues/93 and https://github.com/CYBUTEK/KerbalEngineer/issues/39

### CODE REVIEW

**Comment by harryyoung** [comment]
Video Demonstartion https://www.youtube.com/watch?v=Q0ZK6VkDYRE

**Comment by harryyoung** [comment]
Updated for 1.2

**Comment by harryyoung** [comment]
Updated for current version and ready to pull

**Comment by fat-lobyte** [comment]
Hi, I watched your videos and they look very promising.

I don't know how CYBUTEK runs his Repo, but I believe in the interest of avoiding merge conflicts where there are shouldn't, you should probably not change any files but the source files in question.
Could you maybe edit your branch so that only source code is modified, but no binary or project files?
Are you familiar with Git, especially with `git rebase -i`?
If not, I can assist you with creating an easily-mergable branch.

Hopefully that will increase the chances of CYBUTEK merging, because I love the new readouts!

**Comment by harryyoung** [comment]
fat-lobyte thanks for the offer. I do know how to use console commands in general, however I have never felt the need to use console-git, asI prefer the compforts of GUI for simple tasks. Same goes for git/repo specific files and settings. any help would be appreciated

**Comment by fat-lobyte** [comment]
@harryyoung 

No worries :)
Usually, GitHub for Windows is enough for simple tasks, but there are a few pitfalls and tricks that can only be solved with the command line.

Here's a good source if you want to learn more about git (it's german because I believe you are a german speaker? ;) ):

https://git-scm.com/book/de/v1

I will try to prepare your branch so that it will be easier to merge, and I will notify you when I am done.

**Comment by harryyoung** [comment]
@fat-lobyte Danke!

**Comment by fat-lobyte** [comment]
Alright, I'm done with the branch editing. You can do the following to get the edited branch:
In the git shell, enter the following commands

```
# Add fat-lobyte's repository to remotes
git remote add fat-lobyte https://github.com/fat-lobyte/KerbalEngineer

# retrieve newest commits from fat-lobyte's repository
git fetch fat-lobyte

# Create a branch on your local repository called "deceleration", based on the branch "deceleration-nobin" from fat-lobyte's repository
git checkout -b deceleration fat-lobyte/deceleration-nobin

# publish deceleration branch to your own GitHub repo
git push origin deceleration
```

Further, I would suggest closing this pull request and creating a new one, and selecting the new "deleceration" branch as the head fork.

I have some questions and suggestions for your code, but I will ask them on the new pull request :)

**Comment by harryyoung** [comment]
closed in favor of https://github.com/CYBUTEK/KerbalEngineer/pull/119

**Pull request closed without merging**
